spring:

  datasource:
    url: jdbc:mysql://localhost:3307/test_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 639573a5e7d079727a4db674316d46b1
            client-secret: Kk8pOTAePb2I3axBNX4eLBaKEzapOmER
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: woerifjlsdknvlwijvowienfkwndvokwnodifjpweojfpwojefqpoweknfokweofwneo
  redirect:
    access: http://localhost:8088/login?name=%s&access_token=%s&refresh_token=%s
    register: http://localhost:8088/login?name=%s&access_token=%s&refresh_token=%s
  access-token:
    expiration-time: 3600000
  refresh-token:
    expiration-time: 604800000

server:
  port: 8088
